backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - file: "src/cms/templates/pages/homepage.json"
        name: homepage
        label: Homepage
        format: json
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: homepage
          - label: "Title"
            name: title
            widget: string
            hint: "SEO: title displayed inn browser tab"
          - label: "Test"
            name: test
            options:
              placeholder: my-placeholder
            widget: String


      
